MIME-Version: 1.0
Content-Type: multipart/signed; protocol="application/x-pkcs7-signature"; micalg="sha-256"; boundary="----674E5B4C94B62F75349EC688C87F61BF"

This is an S/MIME signed message

------674E5B4C94B62F75349EC688C87F61BF
delta alpha india victor oscar yankee [QwJCLiGh]
zulu oscar golf xray tango sierra whiskey kilo [NjFTgO1W]
tango charlie tango juliet sierra uniform lima charlie echo delta whiskey [Pwa57zc7]
yankee oscar foxtrot xray november bravo mango echo [t2R85pRR]
xray echo foxtrot mango kilo victor kilo echo hotel victor tango [CdfANHgp]
zulu yankee mango zulu romeo lima charlie tango victor tango papa kilo [aFNZorlk]
papa victor zulu echo india yankee hotel echo [mBPeag54]
oscar golf foxtrot alpha hotel india [aApVcq7u]
yankee juliet quebec whiskey juliet golf yankee echo foxtrot sierra november [fm960799]
mango alpha kilo india delta papa golf yankee papa papa india echo [u5rnpMG2]
sierra bravo bravo quebec victor bravo hotel sierra echo yankee [0Lkh3yAg]
mango alpha xray delta alpha juliet lima delta papa whiskey bravo [R0xTO1Wt]

------674E5B4C94B62F75349EC688C87F61BF
Content-Type: application/x-pkcs7-signature; name="smime.p7s"
Content-Transfer-Encoding: base64
Content-Disposition: attachment; filename="smime.p7s"

MIIFVAYJKoZIhvcNAQcCoIIFRTCCBUECAQExDzANBglghkgBZQMEAgEFADALBgkq
hkiG9w0BBwGgggKQMIICjDCCAfUCCQCwTZ/XSCOQHjANBgkqhkiG9w0BAQsFADBT
MQswCQYDVQQGEwJLUjERMA8GA1UECAwIQ0EtU3RhdGUxEDAOBgNVBAcMB0d3YW5n
anUxDDAKBgNVBAoMA0pOVTERMA8GA1UEAwwIR2lsLURvbmcwHhcNMjYwOTI1MTI1
MTU2WhcNMjcwOTI1MTI1MTU2WjA+MQswCQYDVQQGEwJLUjERMA8GA1UECAwIQ0Et
U3RhdGUxDDAKBgNVBAoMA0pOVTEOMAwGA1UEAwwFQWxpY2UwggEiMA0GCSqGSIb3
DQEBAQUAA4IBDwAwggEKAoIBAQDh05ROYiWnw1nc6bojKy2bl0EvWjbM3arDtZvB
N6eK44g/nK/xy6kcO7F3NMR5Qzj+xovT1jCvsmtnzRiIKgvI0A5r8600sVSMP+LJ
vc1r8ba0CImnP1LZQndeso1NpWL9K8EuN6NsX3Pg+kHoibUH6wwQiz8z07eieYIr
QAh9OqJcvknVZpjEoFl9zlgS4bcMFnLVmHYhq+V39YIxkDWACal/Ex5V4zKDHUr2
W1n/zcPvGRGHrIfrk9XvcAUbHnLFs0094gWmEOAYuB+9Zi1mKrerGwoAn5rmpZfz
63UD4nmdzliM7dJOUdzqXZsmmuWtFpeAg6Z5t8wIEp0zlvutAgMBAAEwDQYJKoZI
hvcNAQELBQADgYEAG2OH1XLPHJu4/eqAtDOf5/bWhSe75yj/383+ZVPNrtcm+cq5
DUNVRov//yMB6SeyifkD5bwwxfeN8yV8sjRv2/YRVnvu6+MMoZCOrszVKBeiHWKN
gPFfGPrwqTm944LJO0d8YXYdGhOAIXWZHXjGqGZU36H8y05WSvX4V34jHyUxggKI
MIIChAIBATBgMFMxCzAJBgNVBAYTAktSMREwDwYDVQQIDAhDQS1TdGF0ZTEQMA4G
A1UEBwwHR3dhbmdqdTEMMAoGA1UECgwDSk5VMREwDwYDVQQDDAhHaWwtRG9uZwIJ
ALBNn9dII5AeMA0GCWCGSAFlAwQCAQUAoIH6MBgGCSqGSIb3DQEJAzELBgkqhkiG
9w0BBwEwHAYJKoZIhvcNAQkFMQ8XDTI2MDkyNTEzMDIxN1owLwYJKoZIhvcNAQkE
MSIEICjih3G+Tx2lJ6mq/jvsEgAJvOOZbtGR7dZmI2bQhHCiMIGOBgkqhkiG9w0B
CQ8xgYAwfjALBglghkgBZQMEASowCAYGKoUDAgIJMAgGBiqFAwICFTALBglghkgB
ZQMEARYwCwYJYIZIAWUDBAECMAoGCCqGSIb3DQMHMA4GCCqGSIb3DQMCAgIAgDAN
BggqhkiG9w0DAgIBQDAHBgUrDgMCBzANBggqhkiG9w0DAgIBKDANBgkqhkiG9w0B
AQEFAASCAQDExx0wBxWDlgEQNNiBNkK2W287IG53def+b8A9yKPhNmhTCtSVg+nE
czepm1mX3cfJp6ypDcta3rJ8w99DEGls6ifhMK64LVbCEdMgKtWXkgd/sffNEeuP
gQ6bs6nLnZepzszRySRWhBARg3WN+mo37ge8/pHoX/AtjjVAKNaPJcV7S8VzOTJW
4/NYdG4MaFAByBN/5hpRGbT8ctjGFtoUmAKl03GKznbrLYcgu4ksnUAQxOlOfaMI
NCvtmChLBfJnkM0h9FxkhqDTmciVZZ+QeHZ4cluT7dEKIl70k3OOSlXsZQKJQQZE
o1hqcGuvw+6EdzmzPl2gOc22VDrz3DGP

------674E5B4C94B62F75349EC688C87F61BF--

